// Code generated by go-validator; DO NOT EDIT.
// Package products contains models and autogenerated validation code
package products

import (
	"unicode/utf8"

	"github.com/shopspring/decimal"
)

// Validate validates struct accordingly to fields tags
func (c createProductRequest) Validate() []string {
	var errs []string
	if c.Name == "" {
		errs = append(errs, "name::is_required")
	}
	if c.Name != "" && utf8.RuneCountInString(c.Name) > 255 {
		errs = append(errs, "name::max_length_is::255")
	}
	if c.Vendor == "" {
		errs = append(errs, "vendor::is_required")
	}
	if c.Vendor != "" && utf8.RuneCountInString(c.Vendor) > 255 {
		errs = append(errs, "vendor::max_length_is::255")
	}
	if c.Description != "" && utf8.RuneCountInString(c.Description) > 10000 {
		errs = append(errs, "description::max_length_is::10000")
	}
	if !c.Price.IsZero() && c.Price.LessThan(decimal.NewFromFloat(0)) {
		errs = append(errs, "price::min_value_is::0")
	}
	if !c.Price.IsZero() && c.Price.GreaterThan(decimal.NewFromFloat(1000000)) {
		errs = append(errs, "price::max_value_is::1000000")
	}

	return errs
}
